name: Build LaTeX document

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main



jobs:
  build_latex:
#     strategy:
#       matrix:
#         name: ['HW_CAD_ASM1','HW_CAD_ASM2','HW_CAD_DET1','HW_CAD_DET2']
    runs-on: ubuntu-latest
    env:
        HW1: 'HW_CAD_DET1'
        HW2: 'HW_CAD_DET2'
        HW3: 'HW_CAD_ASM1'
        HW4: 'HW_CAD_ASM2'
        
        # LAB1: 'CAD_DET1'
        LAB2: 'CAD_DET2'
        LAB3: 'CAD_ASM1'
        LAB4: 'CAD_ASM2'
        
#         LEC1:
        LEC2: 'lec2'
        LEC3: 'lec3'
#         LEC4: 'lec4'
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
#       - name: Compile LaTeX document MaM_${{ matrix.name}}
#         uses: xu-cheng/latex-action@master
#         with:
#           root_file: MaM_${{ matrix.name}}.tex
#           latexmk_use_lualatex: true
#           working_directory: HWs/${{matrix.name}}/

#       - name: Save ${{ matrix.name }} artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: HW_slides
#           path: HWs/${{matrix.name}}/MaM_${{matrix.name}}.pdf    

# HWs
      - name: Compile LaTeX document MaM_${{ env.HW1}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.HW1}}.tex
          latexmk_use_lualatex: true
          working_directory: HWs/${{ env.HW1}}/

      - name: Save ${{ env.HW1}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: HW_slides
          path: HWs/${{ env.HW1}}/MaM_${{ env.HW1}}.pdf

      - name: Compile LaTeX document MaM_${{ env.HW2}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.HW2}}.tex
          latexmk_use_lualatex: true
          working_directory: HWs/${{ env.HW2}}/

      - name: Save ${{ env.HW2}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: HW_slides
          path: HWs/${{ env.HW2}}/MaM_${{ env.HW2}}.pdf

      - name: Compile LaTeX document MaM_${{ env.HW3}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.HW3}}.tex
          latexmk_use_lualatex: true
          working_directory: HWs/${{ env.HW3}}/

      - name: Save ${{ env.HW3}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: HW_slides
          path: HWs/${{ env.HW3}}/MaM_${{ env.HW3}}.pdf
          
      - name: Compile LaTeX document MaM_${{ env.HW4}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.HW4}}.tex
          latexmk_use_lualatex: true
          working_directory: HWs/${{ env.HW4}}/

      - name: Save ${{ env.HW4}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: HW_slides
          path: HWs/${{ env.HW4}}/MaM_${{ env.HW4}}.pdf
          
# LABs
      # - name: Compile LaTeX document MaM_${{ env.LAB1}}
      #   uses: xu-cheng/latex-action@master
      #   with:
      #     root_file: MaM_${{ env.LAB1}}.tex
      #     latexmk_use_lualatex: true
      #     working_directory: labs/${{ env.LAB1}}/

      # - name: Save ${{ env.LAB1}} artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Lab_slides
      #     path: labs/${{ env.LAB1}}/MaM_${{ env.LAB1}}.pdf

      - name: Compile LaTeX document MaM_${{ env.LAB2}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.LAB2}}.tex
          latexmk_use_lualatex: true
          working_directory: labs/${{ env.LAB2}}/

      - name: Save ${{ env.LAB2}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lab_slides
          path: labs/${{ env.LAB2}}/MaM_${{ env.LAB2}}.pdf

      - name: Compile LaTeX document MaM_${{ env.LAB3}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.LAB3}}.tex
          latexmk_use_lualatex: true
          working_directory: labs/${{ env.LAB3}}/

      - name: Save ${{ env.LAB3}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lab_slides
          path: labs/${{ env.LAB3}}/MaM_${{ env.LAB3}}.pdf
          
      - name: Compile LaTeX document MaM_${{ env.LAB4}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.LAB4}}.tex
          latexmk_use_lualatex: true
          working_directory: labs/${{ env.LAB4}}/

      - name: Save ${{ env.LAB4}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lab_slides
          path: labs/${{ env.LAB4}}/MaM_${{ env.LAB4}}.pdf
          
# LECs
#       - name: Compile LaTeX document MaM_${{ env.LEC1}}
#         uses: xu-cheng/latex-action@master
#         with:
#           root_file: MaM_${{ env.LEC1}}.tex
#           latexmk_use_lualatex: true
#           working_directory: lectures/1/

#       - name: Save ${{ env.LEC1}} artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: Lectures_slides
#           path: lectures/1/MaM_${{ env.LEC1}}.pdf

      - name: Compile LaTeX document MaM_${{ env.LEC2}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.LEC2}}.tex
          latexmk_use_lualatex: true
          working_directory: lectures/2/

      - name: Save ${{ env.LEC2}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lectures_slides
          path: lectures/2/MaM_${{ env.LEC2}}.pdf

      - name: Compile LaTeX document MaM_${{ env.LEC3}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ env.LEC3}}.tex
          latexmk_use_lualatex: true
          working_directory: lectures/3/

      - name: Save ${{ env.LEC3}} artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lectures_slides
          path: lectures/3/MaM_${{ env.LEC3}}.pdf
          
      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add HWs/*/*.pdf

          git commit -m "Update compiled PDFs"
          git push
