name: Build LaTeX documents

on: 
  push:
    branches: ['main']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: ghcr.io/xu-cheng/texlive-full:latest
    steps:
      - uses: actions/checkout@v2

      - name: aggregate all tex files
        id: tex-files
        working-directory: src
        run: |
          lectures=$(find ./lectures -name '*.tex' -type f -print0 | xargs -0 printf '%s ')
          homeworks=$(find ./HWs -name '*.tex' -type f -print0 | xargs -0 printf '%s ')
          labs=$(find ./labs -name '*.tex' -type f -print0 | xargs -0 printf '%s ')
          
          # set outputs
          echo "lectures=$lectures" >> $GITHUB_OUTPUT
          echo "homeworks=$homeworks" >> $GITHUB_OUTPUT
          echo "labs=$labs" >> $GITHUB_OUTPUT
    
      - name: echo aggregations
        run: |
          echo "lectures: ${{ steps.tex-files.outputs.lectures }}"
          echo "homeworks: ${{ steps.tex-files.outputs.homeworks }}"
          echo "labs: ${{ steps.tex-files.outputs.labs }}"

      - name: build lectures
        working-directory: src
        run: |
          # for each file in lectures, separated by space
          for file in ${{ steps.tex-files.outputs.lectures }}; do
            # get the file name without extension
            filename=$(basename -- "$file")
            filename="${filename%.*}"
            # compile the file
            latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error -outdir=../out/lectures "$file"
            # move the pdf to out/lectures
            mv "../out/lectures/$filename.pdf" "../out/lectures/$filename.pdf"
          done
      
      - name: build homeworks
        working-directory: src
        run: |
          # for each file in homeworks, separated by space
          for file in ${{ steps.tex-files.outputs.homeworks }}; do
            # get the file name without extension
            filename=$(basename -- "$file")
            filename="${filename%.*}"
            # compile the file
            latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error -outdir=../out/homeworks "$file"
            # move the pdf to out/homeworks
            mv "../out/homeworks/$filename.pdf" "../out/homeworks/$filename.pdf"
          done
      
      - name: build labs
        working-directory: src
        run: |
          # for each file in labs, separated by space
          for file in ${{ steps.tex-files.outputs.labs }}; do
            # get the file name without extension
            filename=$(basename -- "$file")
            filename="${filename%.*}"
            # compile the file
            latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error -outdir=../out/labs "$file"
            # move the pdf to out/labs
            mv "../out/labs/$filename.pdf" "../out/labs/$filename.pdf"
          done


      # # - name: build lectures
      # #   uses: xu-cheng/latex-action@v2
      # #   with: 
      # #     working_directory: ./src
      # #     # sed rewrite %0A to space
      # #     root_file: $(${{ steps.tex-files.outputs.lectures }} | sed 's/%0A/ /g')
      # #     glob_root_files: true
      # #     post_compile: |
      # #       mkdir -p ../out/lectures
      # #       mv *.pdf ../out/lectures

      # - name: build homeworks
      #   uses: xu-cheng/latex-action@v2
      #   with: 
      #     working_directory: ./src
      #     root_file: "${{ steps.tex-files.outputs.homeworks }}"
      #     post_compile: |
      #       mkdir -p ../out/homeworks
      #       mv *.pdf ../out/homeworks

      # - name: build labs
      #   uses: xu-cheng/latex-action@v2
      #   with: 
      #     working_directory: ./src
      #     root_file: "${{ steps.tex-files.outputs.labs }}"
      #     post_compile: |
      #       mkdir -p ../out/labs
      #       mv *.pdf ../out/labs
      
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out'
          author_name: 'GitHub Actions'
          author_email: 
          commit: --signoff
          committer_name: 'Yelshat Duskaliyev'
          committer_email: ura2178@gmail.com
          message: '[auto-ci] added generated pdf'
          pathspec_error_handling: exitImmediately
          