name: Build LaTeX documents

on: 
  push:
    branches: ['main']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: ghcr.io/xu-cheng/texlive-full:latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build lectures
        run: |
          # for each directory in src/lectures
          for dir in src/lectures/*/; do
            if [ ! -f "$dir"*.tex ]; then
              continue
            fi
            cd "$dir"
            for file in "$dir"*.tex; do
              latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=../out/lectures "$file"
            done
            cd ../../..
          done

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out'
          author_name: 'GitHub Actions'
          author_email: 
          commit: --signoff
          committer_name: 'Yelshat Duskaliyev'
          committer_email: ura2178@gmail.com
          message: '[auto-ci] added generated pdf'
          pathspec_error_handling: exitImmediately
          