name: Build LaTeX documents

on: 
  push:
    branches: ['main']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: aggregate all tex files
        id: tex-files
        working-directory: src
        run: |
          lectures=$(find ./lectures -name '*.tex' -type f -print0 | xargs -0 printf '%s\n')
          homeworks=$(find ./HWs -name '*.tex' -type f -print0 | xargs -0 printf '%s\n')
          labs=$(find ./labs -name '*.tex' -type f -print0 | xargs -0 printf '%s\n')
          
          # escape newlines
          lectures="${lectures//$'\n'/'%0A'}"
          labs="${labs//$'\n'/'%0A'}"
          homeworks="${homeworks//$'\n'/'%0A'}"
          
          # set outputs
          echo "lectures=$lectures" >> $GITHUB_OUTPUT
          echo "homeworks=$homeworks" >> $GITHUB_OUTPUT
          echo "labs=$labs" >> $GITHUB_OUTPUT
    
      - name: echo aggregations
        run: |
          echo "lectures: ${{ steps.tex-files.outputs.lectures }}"
          echo "homeworks: ${{ steps.tex-files.outputs.homeworks }}"
          echo "labs: ${{ steps.tex-files.outputs.labs }}"

      - name: build lectures
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./src
          pre_compile: |
            lectures=$(echo ${{ steps.tex-files.outputs.lectures }} | sed 's/%0A/ /g')
          root_file: $lectures
          post_compile: |
            mkdir -p ../out/lectures
            mv *.pdf ../out/lectures

      - name: build homeworks
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./src
          root_file: "${{ steps.tex-files.outputs.homeworks }}"
          post_compile: |
            mkdir -p ../out/homeworks
            mv *.pdf ../out/homeworks

      - name: build labs
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./src
          root_file: "${{ steps.tex-files.outputs.labs }}"
          post_compile: |
            mkdir -p ../out/labs
            mv *.pdf ../out/labs
      
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out'
          author_name: 'GitHub Actions'
          author_email: 
          commit: --signoff
          committer_name: 'Yelshat Duskaliyev'
          committer_email: ura2178@gmail.com
          message: '[auto-ci] added generated pdf'
          pathspec_error_handling: exitImmediately
          