name: Build LaTeX documents

on: 
  push:
    branches: ['main']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: aggregate all tex files
        id: tex-files
        working-directory: src
        run: |
          lectures=""
          for fname in $(find ./lectures -name '*.tex' -type f -print0 | xargs -0); do
            lectures="$lectures$fname\$\'\\n\'"
          done
          homeworks=""
          for fname in $(find ./HWs -name '*.tex' -type f -print0 | xargs -0); do
            homeworks="$homeworks$fname\$\'\\n\'"
          done
          labs=""
          for fname in $(find ./labs -name '*.tex' -type f -print0 | xargs -0); do
            labs="$labs$fname\$\'\\n\'"
          done
          
          echo "Lectures: $lectures"
          echo "Homeworks: $homeworks"
          echo "Labs: $labs"

          echo "lectures=$lectures" >> $GITHUB_OUTPUT
          echo "homeworks=$homeworks" >> $GITHUB_OUTPUT
          echo "labs=$labs" >> $GITHUB_OUTPUT

    
      - name: build lectures
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./src
          root_file: "${{ steps.tex-files.outputs.lectures }}"
          post_compile: |
            mkdir -p ../out/lectures
            mv *.pdf ../out/lectures

      - name: build homeworks
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./src
          root_file: "${{ steps.tex-files.outputs.homeworks }}"
          post_compile: |
            mkdir -p ../out/homeworks
            mv *.pdf ../out/homeworks

      - name: build labs
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./src
          root_file: "${{ steps.tex-files.outputs.labs }}"
          post_compile: |
            mkdir -p ../out/labs
            mv *.pdf ../out/labs
      
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out'
          author_name: 'GitHub Actions'
          author_email: 
          commit: --signoff
          committer_name: 'Yelshat Duskaliyev'
          committer_email: ura2178@gmail.com
          message: '[auto-ci] added generated pdf'
          pathspec_error_handling: exitImmediately
          