name: Build LaTeX documents

on: 
  push:
    branches: ['main']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: aggregate all tex files
        id: tex-files
        working-directory: src
        run: |
          echo "::set-output name=lectures::$(find ./lectures -name '*.tex' -type f -print0 | xargs -0 printf '../%s ')"
          echo "::set-output name=homeworks::$(find ./HWs -name '*.tex' -type f -print0 | xargs -0 printf '../%s ')"
          echo "::set-output name=labs::$(find ./labs -name '*.tex' -type f -print0 | xargs -0 printf '../%s ')"
    
      - name: build lectures
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./out/lectures
          root_file: "{{ steps.tex-files.outputs.lectures }}"

      - name: build homeworks
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./out/homeworks
          root_file: "{{ steps.tex-files.outputs.homeworks }}"

      - name: build labs
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./out/labs
          root_file: "{{ steps.tex-files.outputs.labs }}"
      
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out'
          author_name: 'GitHub Actions'
          author_email: 
          commit: --signoff
          committer_name: 'Yelshat Duskaliyev'
          committer_email: ura2178@gmail.com
          message: '[auto-ci] added generated pdf'
          pathspec_error_handling: exitImmediately
          