name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - closed
    branches:
      - main



jobs:
  build_latex:
    strategy:
      matrix:
        name: ['HW_CAD_ASM1','HW_CAD_ASM2','HW_CAD_DET1','HW_CAD_DET2']
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document MaM_${{ matrix.name}}
        uses: xu-cheng/latex-action@master
        with:
          root_file: MaM_${{ matrix.name}}.tex
          latexmk_use_lualatex: true
          working_directory: HWs/${{matrix.name}}/

      - name: Save ${{ matrix.name }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: slides/MaM_${{matrix.name}}.pdf

      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add slides/*

          git commit -m "Update compiled PDFs"
          git push
