name: Build LaTeX documents

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: aggregate all lecture tex files
        id: lecture-tex-files
        working-directory: src/lectures
        run: |
          echo "::set-output name=paths::$(find . -name '*.tex' -type f -print0 | xargs -0 printf '../%s ')"
      
      - name: aggregate all homework tex files
        id: homework-tex-files
        working-directory: src/HWs
        run: |
          echo "::set-output name=paths::$(find . -name '*.tex' -type f -print0 | xargs -0 printf '../%s ')"
      
      - name: aggregate all lab tex files
        id: lab-tex-files
        working-directory: src/labs
        run: |
          echo "::set-output name=paths::$(find . -name '*.tex' -type f -print0 | xargs -0 printf '../%s ')"

      - name: build lectures
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./out/lectures
          root_file: "{{ steps.lecture-tex-files.outputs.paths }}"
      
      - name: build homeworks
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./out/HWs
          root_file: "{{ steps.homework-tex-files.outputs.paths }}"
      
      - name: build labs
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: ./out/labs
          root_file: "{{ steps.lab-tex-files.outputs.paths }}"
      
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out'
          author_name: 'GitHub Actions'
          author_email: 
          commit: --signoff
          committer_name: 'Yelshat Duskaliyev'
          committer_email: ura2178@gmail.com
          message: '[auto-ci] added generated pdf'
          pathspec_error_handling: exitImmediately
          