name: Build LaTeX documents

on: 
  push:
    branches: ['main']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: ghcr.io/xu-cheng/texlive-full:latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build lectures
        run: |
          srcdir=lectures
          for dir in src/$srcdir/*/; do
            if [ ! -f "$dir"*.tex ]; then
              continue
            fi
            cd "$dir"
            for file in *.tex; do
              latexmk -lualatex -file-line-error -halt-on-error -interaction=nonstopmode -outdir=../../out/$srcdir "$file"
            done
            cd ../../..
          done

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out'
          author_name: 'GitHub Actions'
          author_email: 
          commit: --signoff
          committer_name: 'Yelshat Duskaliyev'
          committer_email: ura2178@gmail.com
          message: '[auto-ci] added generated pdf'
          pathspec_error_handling: exitImmediately
          